spring:
  profiles:
    active:
      -dev

---
spring:
     profiles: dev
     application:
       name: microservicecloud-config-king-dev
---
spring:
     profiles: test
     application:
       name: microservicecloud-config-king-test
